name: build-wheels

on:
  workflow_dispatch:
    branches:
      - master
      - extended

jobs:
  many_linux_wheels:
    name: manylinux-wheels
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
    - uses: actions/checkout@v2

    - name: Print System Information
      run: |
        echo "uname -a: $( uname -a )"
        cat /etc/issue
        echo "Shell: $SHELL"
        echo "Mount points:"; mount
        env

    - name: Chose Python version
      run: |
        ln -s /opt/python/cp39-cp39/bin/python3 /usr/local/bin/python3
        export PATH="/opt/python/cp39-cp39/bin:$PATH"

    - name: Install dependencies
      run: |
        yum install -y libxml2-devel libzstd-devl liblz4-devel liblzma-devel libbzip2-devel
        yum install -y libacl-devel librichacl-devel openssl-devel
        yum install -y librichacl-devel swig strace

    - name: Install python tools
      run: |
        python3 -m pip instal pytest auditwheel

    
    - name: Build libarchive C sources
      run: |
        git clone  git clone https://github.com/libarchive/libarchive.git libarchive-src    
        cd libarchive-src; git checkout 3.5
        mkdir build; cd build
        cmake ../
        make -j$(nproc);  make install
        cd ../..


    - name: Compile pyhton modules
      run: |
        rm -rf build wheelhouse
        touch libarchive/_libarchive.i
        export LD_LIBRARY_PATH=/usr/local/lib64/:/usr/local/lib:$LD_LIBRARY_PATH
        export LIBARCHIVE_PREFIX=/usr/local
        python3 setup.py install


    - name: Build wheels
      run: |
        pip wheel --wheel-dir dist/ .
        auditwheel repair dist/*.whl
        python3 -m pip install --force-reinstall wheelhouse/*,whl

    