name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy to PyPI
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build the library
      env:
        PYVER: ${{ matrix.version }}
      run: python3 setup.py sdist

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
